apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: landmark-devops
data:
  NODE_ENV: production

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: landmark-devops
type: Opaque
stringData:
  DATABASE_URL: mysql://landmark:landmark123@db:3306/landmark_devops
