apiVersion: v1
kind: ServiceAccount
metadata:
  name: landmark-app
  namespace: landmark-devops

---
# Role — defines what actions are allowed
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: landmark-app-role
  namespace: landmark-devops
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding — attaches the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: landmark-app-rolebinding
  namespace: landmark-devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: landmark-app-role
subjects:
  - kind: ServiceAccount
    name: landmark-app
    namespace: landmark-devops
